#!/usr/bin/env bash
# Tells a story about each user in /etc/passwd using a while loop and IFS
while IFS=":" read -r username password userid groupid info home shell
do
      echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $useriplace is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
